CREATE TABLE atdVacRecord
(
    SEQ NUMBER PRIMARY KEY ,
    ESEQ NUMBER NOT NULL REFERENCES EMPLOYEE(SEQ),
    CSEQ NUMBER NOT NULL REFERENCES atdVrcategory(SEQ),
    LEAVETIME DATE NOT NULL ,
    COMETIME DATE NOT NULL ,
    MEMO VARCHAR2(2000) NULL
);