CREATE TABLE atdbcomment
(
	seq NUMBER PRIMARY KEY,
	eseq NUMBER NOT NULL REFERENCES employee(seq),
	bseq NUMBER NOT NULL REFERENCES atdboard(seq),
	regdate DATE DEFAULT sysdate,
	CONTENT VARCHAR2(2000) NOT NULL,
	THREAD NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL
);