CREATE TABLE atdEtcRecord
(
    SEQ NUMBER PRIMARY KEY,
    WRSEQ NUMBER NOT NULL REFERENCES atdWorkRecord(SEQ),
    LEAVEtime DATE NOT NULL,
    COMETIME DATE NOT NULL,
    MEMO VARCHAR2(2000) NULL
);